// ============================================================================
// Farm Sim — Terrain tile sprites (16×16 px each).
// Palette keys: see palette.ts. '.' = transparent.
//
// Each tile is 16×16. They tile seamlessly (edges designed to match neighbours).
// Wet-soil state is visible as a darker, shinier version — this IS the moisture UI.
// ============================================================================

import { sprite, SpriteGrid } from './spriteUtil';

// ── GRASS ───────────────────────────────────────────────────────────────────
// Three variants for visual variety (chosen by tile index % 3).

export const GRASS_A: SpriteGrid = sprite(`
HHHHHIHHHHHHIHHH
HGHHHHHIHHHHHHIH
HHHHGHHHHHHGHHHI
IHHHHHHHHGHHHHHH
HHHHHIHHHHHIHHGH
HHGHHHHHIHHHHHHI
HHHHHHHGHHHHHHHH
IHHHHHHHHHGHHHHI
HHHGHHHHHHHHHHHH
HHHHHIHHHHHIHHGH
HHHHHHHHGHHHHHHI
GHHHHHHHHHGHHHHI
HHHIHHHHHHHHHGHH
HHHHHHHGHHHHHHHH
IHHHHHHHHGHHHHHH
HHHGHHHHHHHIHHHH
`);

export const GRASS_B: SpriteGrid = sprite(`
IHHHHHGHHHHHIHHH
HHGHHHHHHHGHHHIH
HHHHIHHHHHHHHHHG
HHHHHHHGHHHIHHHI
GHHHHHHHHHHHHHGH
HHHIHHHHGHHHHHHI
HHHHHHHHHHGHHHGG
IHHHGHHHHHHHHHHI
HHHHHHHIHHHHHHHH
GHHHHHHHHHGHHHHI
HHHGHHHHHHHHHHHH
HHHHHIHHHGHHHHHG
HHHHHHHHHHHHIGHH
GHHHHHHHGHHHHHHI
IHHHHHHHHHHHHHGH
HHGHHHHHHHIHHHHI
`);

export const GRASS_C: SpriteGrid = sprite(`
HHHGHHHHHHHIHHIH
HHHHHHIHHGHHHHHH
GHHHHHHHHHHHHHGI
HHHIHHHHHHHHHHGH
HHHHHHGHHHHIHHHI
IHHHHHHHHHGHHHHI
HHHHHHHHHHHHHHHG
GHHHHGHHHHHHIHHI
HHHHHHHHHHHHHHHH
HHGHHHHHIHHHHHGH
HHHHHHHGHHHHHHHH
IHHHHHHHHHHIHHHG
HHHHGHHHHHHHHHHH
HHHHHHHIHHHGHHHG
HHGHHHHHHHHHHHHI
HHHHHIHHHHHHHGHH
`);

// ── TILLED SOIL — DRY ───────────────────────────────────────────────────────
export const TILLED_DRY: SpriteGrid = sprite(`
0000000000000000
0ABABABABABABA00
0BABABABABABABAB
0ABABABABABABA00
0BABABABABABABAB
0ABABABABABABA00
0BABABABABABABAB
0ABABABABABABA00
0BABABABABABABAB
0ABABABABABABA00
0BABABABABABABAB
0ABABABABABABA00
0BABABABABABABAB
0ABABABABABABA00
0BABABABABABABAB
0000000000000000
`);

// ── TILLED SOIL — WET (darker + sheen line) ─────────────────────────────────
export const TILLED_WET: SpriteGrid = sprite(`
0000000000000000
0DEDEDEDEDEDEDE0
0EDEDEDEDEDEDEDE
0DEDEDEDEDEDEDE0
0EDEDEDEDEDEDEDE
0DEDEDEDEDEDEDE0
0EDEDEDEDEDEDEQ0
0DEDEDEDEDEDEDE0
0EDEDEDEDEDEDED0
0DEDEDEDEDEDEDE0
0QDEDEQEDEDEDED0
0DEDEDEDEDEDEDE0
0EDEDEDEDEDEDED0
0DEDEDEDEDEDEDE0
0EDEDEDEDEDEDEDE
0000000000000000
`);

// ── LOCKED TILE (hedge / boundary) ──────────────────────────────────────────
export const LOCKED: SpriteGrid = sprite(`
JIJIJIJIJIJIJIJJ
IIJIJIJIJIJIJIJI
JIJIJIJIJIJIJIJJ
IJIJIJIJIJIJIJIJJ
JIJIJIJIJIJIJIJJ
IIJIJIJIJIJIJIJI
JIJIJIJIJIJIJIJJ
IJIJIJIJIJIJIJIJJ
JIJIJIJIJIJIJIJJ
IIJIJIJIJIJIJIJI
JIJIJIJIJIJIJIJJ
IJIJIJIJIJIJIJIJJ
JIJIJIJIJIJIJIJJ
IIJIJIJIJIJIJIJI
JIJIJIJIJIJIJIJJ
IJIJIJIJIJIJIJIJJ
`);

// ── RESERVOIR ───────────────────────────────────────────────────────────────
// 2×2 tile footprint; this is the top-left cell (16×16) — renderer tiles 4 of them.
export const RESERVOIR_TL: SpriteGrid = sprite(`
RRRRRRRRSSSSSSSS
RRRRRRRRSSSSSSS0
RRRRRRR0SSSSSSS0
RRRRRR00MMMMMMM0
RRRRR0MMMNNNMM00
RRRR0MNNNOOONNM0
RRR00MNNOOPOONN0
RRS0QMNNOOOONNM0
RS00MNNOOONNNNM0
R0MMNNOOOONNMM00
00MNNNOOONNMMM00
0MNNNOONNMMMM000
0MNNNOOOMMMM0000
0MNNNMMMMMM00000
0MMMMMMMM0000000
00000000000000000
`);

// ── CHANNEL — horizontal ─────────────────────────────────────────────────────
export const CHANNEL_H: SpriteGrid = sprite(`
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
00000000000000000
0NNNNNNNNNNNNNNN
0OOOOOOOOOOOOOON
0NNNNNNNNNNNNNNN
00000000000000000
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
`);

// ── CHANNEL — vertical ───────────────────────────────────────────────────────
export const CHANNEL_V: SpriteGrid = sprite(`
HHHHH00HHHHHHHHH
HHHHH0N0HHHHHHH0
HHHHH0O0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH0O0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH0O0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH0O0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH0O0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH0O0HHHHHHH0
HHHHH0N0HHHHHHH0
HHHHH00HHHHHHHHH
`);

// ── WELL ─────────────────────────────────────────────────────────────────────
export const WELL: SpriteGrid = sprite(`
HHHHHHHHHHHHHHH0
HHHHH0WWWW0HHHH0
HHHH0WVVVVW0HHHH
HHH0WVVVVVVW0HHH
HH0WVVVMMMVVW0HH
HH0WVVMNNMVVW0HH
HH0WVVMNOMVVW0HH
HH0WVVMNNMVVW0HH
HH0WVVVMMMVVW0HH
HH0WVVVVVVVW0HHH
HHH0WXXXXXXW0HHH
HHHH0UUUUUU0HHHH
HHHHH0TTTT0HHHHH
HHHHHH0SS0HHHHHH
HHHHHHHHHHHHHHH0
HHHHHHHHHHHHHHHH
`);

// Export map: TileKind → sprite (some have multiple for animation/bitmask)
export type TileSprite = {
  grass: [SpriteGrid, SpriteGrid, SpriteGrid];
  tilledDry: SpriteGrid;
  tilledWet: SpriteGrid;
  locked: SpriteGrid;
  reservoirTL: SpriteGrid;
  channelH: SpriteGrid;
  channelV: SpriteGrid;
  well: SpriteGrid;
};

export const TILE_SPRITES: TileSprite = {
  grass: [GRASS_A, GRASS_B, GRASS_C],
  tilledDry: TILLED_DRY,
  tilledWet: TILLED_WET,
  locked: LOCKED,
  reservoirTL: RESERVOIR_TL,
  channelH: CHANNEL_H,
  channelV: CHANNEL_V,
  well: WELL,
};
