// Terrain tile sprites. Every export is a 16x16 SpriteGrid.
import { sprite, SpriteGrid } from './spriteUtil';

export const GRASS_A: SpriteGrid = sprite(`
HHHHHHHHHHHHHHHH
HHHHIHHHHHHHHHHH
HHHHHHHHHHIHHHHH
HHHHHHHHHHHHHHHH
HHIHHHHHHHHHHIHH
HHHHHHHHHHHHHHHH
HHHHHHIHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHIHHHHH
HHIHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHIHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHIHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHIHHHHHHH
`);

export const GRASS_B: SpriteGrid = sprite(`
HHHHHHHHHHHHHHHH
HHHHHHHHIHHHHHHH
HHHHHHHHHHHHHHHH
HHIHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHIHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHIHHHHH
HHHHHHHHHHHHHHHH
HHHHIHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHIHHHHHHH
HHHHHHHHHHHHHHHH
HHIHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHIHHH
`);

export const GRASS_C: SpriteGrid = sprite(`
HHHHIHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHIHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHIHHHHHHH
HHHHHHHHHHHHHHHH
IHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHIHHH
HHHHHHHHHHHHHHHH
HHHHIHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHIHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHIHHHHH
HHHHHHHHHHHHHHHH
`);

export const TILLED_DRY: SpriteGrid = sprite(`
CCCCCCCCCCCCCCCC
CABABABABABABABC
CBABABABABABABAC
CABABABABABABABC
CBABABABABABABAC
CABABABABABABABC
CBABABABABABABAC
CABABABABABABABC
CBABABABABABABAC
CABABABABABABABC
CBABABABABABABAC
CABABABABABABABC
CBABABABABABABAC
CABABABABABABABC
CBABABABABABABAC
CCCCCCCCCCCCCCCC
`);

export const TILLED_WET: SpriteGrid = sprite(`
FFFFFFFFFFFFFFFF
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FDEDEDEDEDEDEDEF
FEDFEDEDEDEDEFDE
FFFFFFFFFFFFFFFF
`);

export const LOCKED: SpriteGrid = sprite(`
JJJJJJJJJJJJJJJJ
JJJJIJJJJJJJJJJJ
JJJJJJJJJIJJJJJJ
JJJJJJJJJJJJJJJJ
JIJJJJJJJJJJIJJJ
JJJJJJJJJJJJJJJJ
JJJJJJIJJJJJJJJJ
JJJJJJJJJJJJJJJJ
JJJJJJJJJJIJJJJJ
JJIJJJJJJJJJJJJJ
JJJJJJJJJJJJJJJJ
JJJJIJJJJJJJJJJJ
JJJJJJJJJJJJJJJJ
JJJJJJIJJJJJJJJJ
JJJJJJJJJJJJJJJJ
JJJJJJJJIJJJJJJJ
`);

export const RESERVOIR_TL: SpriteGrid = sprite(`
RRRRRRRSSSSSSSS0
RRRRRRR0SSSSSSS0
RRRRRR0MMMMMMM00
RRRRR0MMMNNNMM00
RRRR0MNNNOOONNM0
RRR0MNNNOOPOONN0
RR0QMNNOOOONNM00
R00MNNOOONNNNM00
0MMNNOOOONNMM000
0MNNNOOONNMMM000
0MNNNOONNMMMM000
0MNNNOOOMMMM0000
0MNNNMMMMMM00000
0MMMMMMMMM000000
0000000000000000
0000000000000000
`);

export const CHANNEL_H: SpriteGrid = sprite(`
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
0000000000000000
0NNNNNNNNNNNNNN0
0NOOOOOOOOOOOON0
0NNNNNNNNNNNNNN0
0000000000000000
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
`);

export const CHANNEL_V: SpriteGrid = sprite(`
HHHHH00HHHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0O0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0O0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0O0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0O0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0O0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH0O0HHHHHHHH
HHHHH0N0HHHHHHHH
HHHHH00HHHHHHHHH
`);

export const WELL: SpriteGrid = sprite(`
HHHHHHHHHHHHHHHH
HHHHH0WWWW0HHHHH
HHHH0WVVVVW0HHHH
HHH0WVVVVVVW0HHH
HH0WVVVMMMVVW0HH
HH0WVVMNNMVVW0HH
HH0WVVMNOMVVW0HH
HH0WVVMNNMVVW0HH
HH0WVVVMMMVVW0HH
HH0WVVVVVVVW0HHH
HHH0WXXXXXXW0HHH
HHHH0UUUUUU0HHHH
HHHHH0TTTT0HHHHH
HHHHHH0SS0HHHHHH
HHHHHHHHHHHHHHHH
HHHHHHHHHHHHHHHH
`);

export const PATH: SpriteGrid = sprite(`
AAAAAAAAAAAAAAAA
ABAAAAAAAAAAAAAA
AAAAAAAABAAAAAAA
AAAAAAAAAAAAABAA
AAABAAAAAAAAAAAA
AAAAAAAAAABAAAAA
AAAAAAAAAAAAAAAB
AAAAAAABAAAAAAAB
AAAAAAAAAAAAAAAA
ABAAAAAAAABAAAAA
AAAAAAAABAAAAAAA
AAAAAAAAAAAAABAA
AAAABAAAAAAAAAAA
AAAAAAAAAAAAAABA
AAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAA
`);

export type TileSprite = {
  grass: [SpriteGrid, SpriteGrid, SpriteGrid]; tilledDry: SpriteGrid; tilledWet: SpriteGrid;
  locked: SpriteGrid; reservoirTL: SpriteGrid; channelH: SpriteGrid; channelV: SpriteGrid;
  well: SpriteGrid; path: SpriteGrid;
};

export const TILE_SPRITES: TileSprite = {
  grass: [GRASS_A, GRASS_B, GRASS_C], tilledDry: TILLED_DRY, tilledWet: TILLED_WET,
  locked: LOCKED, reservoirTL: RESERVOIR_TL, channelH: CHANNEL_H, channelV: CHANNEL_V,
  well: WELL, path: PATH,
};
